- app/client/zones-toolbox.hbs.html
- app/client/zones-toolbox.scss
Make popup keep working with long zone name
s
> fix: zone-toolbox editor

- app/client/lemverse.scss
- app/client/tileset-toolbox.hbs.html
- app/client/tileset-toolbox.js
- app/client/tileset-toolbox.scss
This was reported by 4 users who didn't get info of tile.
As it was reported there : https://github.com/l3mpire/lemverse/issues/33
After few iteration i got this as starting point to refactor the design of selected and pointer design.
Now:
Before:
The red border represent the colision information
Pointer and selection have move to new column
Tile design fit to tile eraser design
Removed pixel position
Change tile postion format from `(14/7)` to `x: 14 y: 7`
> feat: add colision in tileset-editor and refactor design

- README.md
Hey there!
I don't know why the table of contents is the way it is, but removing some dashes is necessary to make it work on GitHub.
> Make the README's Table of contents functional on GitHub :)

- .dockerignore
- Dockerfile
- Dockerfile.dev
- docker-compose.yml
Without this PR, lemverse in Docker results in a white screen, because `core` isn't copied in the images so there isn't much to send to the clients. I've added as well a few other things that I found while debugging this; commits should be self-explanatory.
> Fix and improve Docker things

- README.md
- app/_settings.json
- app/settings-dev.json
- core/client/helpers.js
- core/client/scenes/scene-world.js
- add configurable zoom settings
- set default zoom at start-up
- add linear zooming (zoom out become gradually slower)
- clamp zoom to world bounds (prevent zooming out when the map reach its full height or width)
- fix the zoom direction
A `maxDelta` parameter has been added, it allows to avoid savage zooming out in one shot
using mouse wheel.
> Improve world zoom

- core/client/peer.js
- core/server/analytics.js
`DiscussionAttend` and `DiscussionEnd` events are now thrown also when a user joins or leaves an existing discussion.
`users_attending_count`: This property allows to know how many users were in the discussions before the join/left and thus allows to filter new discussions/discussions ending if needed.
`peer_user_id:` The user id of the user joining/leaving the discussion.
The choice of throwing the same events with a `users_attending_count` rather than new events (e.g. `DiscussionJoin`, `DiscussionLeft`) is because it is easier in most analytics tools to filter on properties rather than aggregating events.
> Improve discussions analytics

- core/client/ui/editor-tilesets.js
- core/server/files.js
Fixing issue https://github.com/l3mpire/lemverse/issues/82
The problem was that upload is asynchronous and at the same time, each new uploaded tiles have a `gid` value wich is based on the last uploaded tiles. But using asynchronous and trying to have the last uploaded item is not compatible.
I fixed it by adding a `gid` property to new uploaded files before uploading tiles asynchronously, and now we use this gid in asynchronous tiles uploading
> Fix tilesets bug having same gid

- app/_settings.json
- app/settings-dev.json
- core/modules/meet/client/meet.js
Actually we can't override Jitsi meet options as we can found them here : https://github.com/jitsi/jitsi-meet/blob/master/config.js
I've added a simple solution to override it dynamically.
> Add possibility to override jitsi meet config options

- core/client/ui/form-account.hbs.html
- core/client/ui/form-account.js
- core/client/ui/form-log-in.hbs.html
- core/client/ui/form-log-in.js
- core/client/ui/form-sign-in-limited.hbs.html
- core/client/ui/form-sign-in-limited.js
When `public.lp.permissions.allowAccountCreation` is `"none"`, the login form currently looks like this:
With this PR applied, it now looks that way:
Also, if you don't specify a `public.lp.permissions.contactURL`, then `allowAccountCreation` is currently ignored. With this PR applied, it applies but just don't show the "Contact us" message:
> Rework account restriction system

- core/server/accounts.js
Rename `Sign In` event to `Log In` and throws it even when the user resume log-in.
The property `type` (`password` or `resume`) allows to track both types of log-in.
> Improve log-in analytics

- core/server/accounts.js
- core/server/analytics.js
- core/server/users.js
As recommended by Segment documentation, identify is now also called at log-in.
(https://segment.com/docs/connections/spec/identify/)
Reserved and custom traits have now a more distinct separation as they are handled a bit differently by Segment ($ prefix or case handling for instance).
https://segment.com/docs/connections/spec/identify/#traits
> Improve identifying analytics

- README.md
- app/_settings.json
- app/settings-dev.json
- core/client/ui/settings-main.hbs.html
- core/client/ui/settings-main.js
When `allowProfileEdition` is false, the `My account` tab is not shown in the user settings.
> Add configurable profile edition

- README.md
- app/_settings.json
- app/settings-dev.json
- core/client/peer.js
I moved the name of the sound files to be played on an incoming call or at the end of a call to a configuration file to remove the raw values from the code and be able to choose other sounds
> Move sounds configuration to settings

- core/client/entity-manager.js
- core/client/scenes/scene-world.js
The first (small) step in improving performance.
In most cases the simulation logic does not need to be run at 60 FPS (unlike rendering). In most game engines there are few update methods which not exists in web due to the `requestAnimationFrame` usage: 
- One for physics (depends on the project settings, usually 20 times per second)
- One for the rendering (60 times per second)
- One for the rest of the logic
The chrome profiler indicated that the detection of close entities was a bit greedy, by moving this logic in a function executed less often I decrease the CPU usage a little bit.
> Entity performance improvement

- core/client/character-pop-ins.js
Making shallow copy of popInConfiguration to avoid reference of `const config`. Actually, when we use `position: relative` on popInConfiguration. The `config.x` and `config.y` will be increment exponentially due to this copy of reference instead of shallow copy, because each time we reuse `const config`it will save the same value of previous iteration and increment it to the user position.
> Fix relative popInConfiguration broken

- core/server/users.js
Latency issues make it possible for a user to spam the Sign Up button. It should be disabled on the front side, for the moment I fixed the back side
> Avoids converting a guest account multiple times

- core/client/ui/levels.js
- core/client/ui/user-panel.hbs.html
- core/client/ui/user-panel.js
- core/client/ui/user-panel.scss
- core/modules/textual-communication-tools/client/textual-communication-tools.js
Add in settings
```json
{
"public": {
"disabledFeatures": ["textualCommunicationTools"]
}
}
```
> 1 - Developer can disabled tchat tools in settings

- core/client/ui/user-profile.hbs.html
- core/client/ui/user-profile.scss
Fixes #165 
Add feature for converting users website into a `clickable` link. 
if the user has no website, then it just shows a dash.
> Fixes #165: Make website in profile popup clickable link

- .gitignore
- core/client/ui/form-log-in.hbs.html
- core/client/ui/form-log-in.js
- core/client/ui/form-sign-in.hbs.html
- core/client/ui/form-sign-in.js
- core/client/ui/settings-main.hbs.html
- core/client/ui/settings-main.js
Fixes #126 
I just searched for usages of `Meteor.settings...` as a helper and replaced them.
I only kept the `contactURL` helper because it shims the potential undefined `Meteor.settings.public.permissions` property. Maybe this should be replaced to?
I also realized that many helpers with `Template.instance()` exists and could be replaced with the global `instance` helper:
https://github.com/l3mpire/lemverse/blob/cf70039679d74fd4fc4ee17fcdabf1e1f25807f2/app/packages/lempire/lempire-helpers.js#L25
But just because these are much more (44 usages in 21 files), it should be done in a separate issue ☺️
> Rationalize settings template helpers

- core/client/audio-manager.js
- core/lib/misc.js
- core/modules/punch-ability/client/punch-ability.js
Fixes #167
Updates the punch ability to play pitched with a random value between `0.7` and `1.5`.
This is only possible on an [`AudioBuffer`](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer), that's why I had to add a method to load the audio buffer from the URL.
See attached video (with sound ;) )
https://user-images.githubusercontent.com/6061136/196361057-fe72ac74-c0e8-41cf-9bc0-c7ed39d4b574.mp4
> Play punched sound with a random pitch

- core/client/ui/settings-main.js
During the logout there is a short lapse of time where Meteor.user() is null, if the logout is performed on character or media settings screen the reactive template helpers are called and throw errors.
> Fix logout errors

- core/modules/messages/client/messages.js
A notification was sent to all users of the current zone when a message was aimed at another zone, the bug is not possible by default but with the arrival of channels in the left menu it is possible to discuss in a remote zone.
> Stop sending WebRTC notifications when the targeted channel is not the active zone

- core/client/ui/editor-tilesets.js
When `selectedTileset()` is called in an handlebars template, a new cursor with an observer is created for each call (e.g `tile2domX`, `tile2domY`, etc), meaning that, for a large template, when a tileset is edited (for collision or layering), Meteor does literally thousands of local Minimongo updates of the tileset document copies, taking several seconds to perform.
This part might need a bigger refactoring but in the meanwhile I suggest this small optimization which allows to create a new observer only when the selected tileset changes.
> Optimize tileset edition

- core/client/user-manager.js
- core/server/users.js
Retrieves the user's status and updates it to inactive in the focus rooms. The purpose is to use this status to indicate when a user is not available
> Update user status in setUserInDoNotDisturbMode

- core/client/entity-manager.js
- core/client/helpers.js
- core/client/ui/toolboxes/entity-editor.hbs.html
- core/client/ui/toolboxes/entity-editor.js
- core/client/ui/toolboxes/entity-editor.scss
- core/client/user-manager.js
Allows users to use entities other than to change a state from true to false. 
I've added the ability to open a URL like for zones. Unlike zones, the opening is not automatic, which is less intrusive. You just have to move to stop the interaction, I will add the "Escape" key later.
https://user-images.githubusercontent.com/3781087/199770968-c9841da2-8dc4-457f-a337-d4186335f00c.mov
> Allow custom interactions on entities

- core/client/ui/user-profile.hbs.html
- core/client/ui/user-profile.js
- core/modules/messages/client/messages-list.hbs.html
- core/modules/messages/client/messages-list.js
- core/modules/messages/client/messages-list.scss
- core/modules/notifications/client/notifications.hbs.html
- core/modules/notifications/client/notifications.scss
- core/modules/report/client/report.hbs.html
- core/modules/report/client/report.js
- core/modules/report/client/report.scss
Add a report option.
Useful to report an user or a message.
Available in:
- profile
- radial menu
- messages
[video](https://user-images.githubusercontent.com/34689945/195100347-dd9008cd-41ba-4a0b-aa10-3735550c1311.mp4)
> Report users

- core/client/ui/toolboxes/entity-editor.js
Allows level editors to link a switch to any type of entity that cannot be collected
> Entities: show all non-pickable entities in the target list

- README.md
- core/client/passwordless.js
- core/server/accounts.js
Allow users to login using a JWT provided in query param.
For instance: `https://app.lemverse.com?token={jwt_token}`
The minimal required payload is the user email in the `sub` claim:
```json
{
"sub": "user@example.com"
}
```
Additional standard claims can be used (for instance to limit the token validity in a time range):
```json
{
"sub": "user@example.com",
"nbf": 1667563200,
"exp": 1667570400,
}
```
and a custom `level_id` claim allows to log-in a user in a specific level:
```json
{
"sub": "user@example.com",
"level_id": "lvl_nENCytZvbcHhxsFSt"
}
```
When `"jwtAuthSecret"` is not provided in the settings, the JWT login handler is completely disabled.
This feature allows to generate time ranged login links from a third party app.
> Add JWT user login

- core/client/helpers.js
Actually, if you pass to fast near user, sometimes the connection can stay open. This is due to the way we check the distance between the users. We pass a user object between all function in the process and when finally we check if we have to keep the connection open, the user may have already moved but we have the default value when the process began. 
The fix is really simple, just fetching the user current position when we need to check the distances between them.
> Fix call not closing when passing to fast near user

- core/client/ui/editor-tilesets.js
- core/client/ui/toolboxes/tileset-toolbox.js
When tilesets has value `hidden: false` it was considered as hidden because we are checking if value exist and not if it's false.
> Fix broken tilesets

- core/client/ui/levels.js
- core/server/levels.js
This fix a "bug", when switching level, we use the user current position to the next level and sometime we can spawn in a wall, making the user blocked and can't moove.
> Use level spawn position when switching level

- core/modules/console/client/console.hbs.html
- core/modules/console/client/console.js
- core/modules/console/client/console.scss
- core/modules/messages/client/helpers.js
- core/modules/messages/client/messages-list.hbs.html
- core/modules/messages/client/messages-list.js
- core/modules/messages/client/messages-list.scss
- core/modules/textual-communication-tools/client/textual-communication-tools.scss
Separates the display logic of the messages module from the console. This will allow to customize the console interface or to use the console in a different way (launch commands for example)
> Messages: split console state from the message module

- app/settings-dev.json
- core/client/helpers.js
- core/client/network-manager.js
- core/client/peer.js
- core/client/user-manager.js
- core/client/user-voice-recorder-ability.js
- core/modules/punch-ability/client/punch-ability.js
- Moves the activation/deactivation logic of the peers to the peer module
- Use the network manager to send data: It will be useful later if you don't want to use Peerjs anymore
- Reconnect the peer on disconnect
- Reduce the alive timeout to fix issues with the "id already taken" message
> Enhance peer

- README.md
- app/_settings.json
- app/settings-dev.json
- core/client/lemverse.hbs.html
- core/client/lemverse.js
- core/server/accounts.js
When form login is disabled, a user can only login to his account using a JWT. Resuming and guest login are still allowed.
If the setting is not provided nothing is changed (form login is disabled only when `allowFormLogin` is false).
> Add a setting to disable form login

- core/client/ui/toolboxes/entity-editor.hbs.html
- core/client/ui/toolboxes/entity-editor.js
This pull request adds the posibility so set the depth of the entities above layer 6.
> Add map on entity depth

- core/client/character-pop-ins.js
This pull request allows the user to use a unit other than pixels.
```json
{
"name": "",
...
"popInConfiguration": {
"width": "29.5vw",
"height": "22.5vw",
"position": "center",
"yt": true,
"className": "wood-style with-arrow fade-in v-centered",
"offset": {
"x": 0,
"y": 0
}
},
...
}
```
> Change dimension pop-in configuration

- core/client/scenes/scene-world.js
- core/client/url-opener.js
This pull request adds the possibility to add css on the main iframe.
This allows us, for example, to set the z-index of a page to be on top of all other popups.
```json
{
"url": "https://link",
"style": {
"z-index": 20
}
}
```
> Add style for zone

- app/_settings.json
- app/settings-dev.json
- core/client/lemverse.js
- core/client/peer.js
- core/client/ui/remote-stream.hbs.html
- core/client/ui/remote-stream.js
- core/client/ui/settings-medias.js
- core/client/user-streams.js
- Add a fallback when the unsplash API is down or the remote image is not found
- Stop updating many things on user update
- Remote user's avatar is now updated when the user is updating his avatar
> Add fallback on remote user's avatar& add reactivity on the avatar

- core/client/ui/user-onboarding.scss
Limit on-boarding image size to avoid scroll bar and continue button pushed out of the screen for small screen resolution.
Before:
After:
> Limit on-boarding image size
