l3mpire/lemverse

- .dockerignore
- Dockerfile
- Dockerfile.dev
- README.md
This add allow developper to build docker machine with lemverse in it .
I choose docker base image from https://github.com/disney/meteor-base 
it allow us to build into the docker. and produce output image without build tools
> add Dockerfile 

- app/client/zones.js
Popup need to be close each time you hit admin zone.
it can be more smooth for user to have notif instead
> feat: Change popup to notif for admin zone

- .eslintrc.js
- README.md
- app/_settings.json
- app/client/lemverse.scss
- app/client/peer.js
- app/client/user-streams.js
- app/lib/misc.js
- app/settings-dev.json
Instead of having fixed list of random photo. 
we can use robothash API to get unique image of cat from username encoded.
> feat: add unique cat image when video not shared

- README.md
- example/docker-compose-prod/Caddyfile
- example/docker-compose-prod/README.md
- example/docker-compose-prod/docker-compose.yml
- example/docker-compose-prod/jitsi/.env.exemple
- example/docker-compose-prod/jitsi/README.md
- example/docker-compose-prod/jitsi/docker-compose.yml
- example/docker-compose-prod/jitsi/gen_env.sh
This add a complete exemple for docker deployment
> feat: add docker-config for production

- app/client/settings-main.js
> fix: sharelink

- core/client/scenes/scene-world.js
- core/client/ui/user-panel.js
- core/client/ui/user-panel.scss
- Fixes event problems that don't work on mobile
- Blocks events on interface elements
Close issue #91
> mobile: fix issue with actions not triggered

- core/client/ui/modal.scss
- core/client/ui/team.scss
- core/client/ui/user-invitation.hbs.html
- core/client/ui/user-list-selection.hbs.html
- core/client/ui/user-list-selection.scss
- core/client/ui/user-list.hbs.html
- core/client/ui/user-list.scss
> 1 - ui: fix invalid modal layout with scrollable content

- core/server/accounts.js
- core/server/analytics.js
- core/server/guilds.js
- core/server/users.js
- Fix issue with groups
- Send analytic event when the user update his profile
- Add group to the following events: Sign In & Log Out
> Fix analytics (groups & users)

- core/server/accounts.js
When a user has the `disabled` property, he cannot log-in nor receive passwordless emails.
The `Meteor.call('requestLoginTokenForUser', options);` on the server side is required because `requestLoginTokenForUser` is registered as a Meteor method in the `accounts-passwordless` package.
As stated in the `Meteor.call` documentation (https://docs.meteor.com/api/methods.html#Meteor-call), the call is performed synchronously as no callback is provided.
> Allows account deactivation

- core/client/peer.js
The modification of this part allows to better manage the sending of streams to other users: It now allows to delete a track from a call
> Allows the user to remove tracks from a stream

- app/_settings.json
- app/package-lock.json
- app/package.json
- app/settings-dev.json
- core/client/lemverse.js
- core/client/sentry.js
- core/server/main.js
- core/server/sentry.js
> Add support for Sentry

- core/client/peer.js
> 1 - peer: avoids stopping a call when the communication is marked as locked

- core/client/components/character-name-text.js
- core/client/components/character.js
- core/client/scenes/scene-ui.js
- core/client/ui/settings-basic.hbs.html
- core/client/ui/settings-basic.js
- core/client/user-manager.js
- core/server/users.js
Add a new `Baseline` setting allowing to set a baseline with a smaller font size under the user name.
When provided:
When not provided:
> Add a name baseline

- README.md
- app/_settings.json
- app/settings-dev.json
- core/client/ui/settings-main.hbs.html
- core/client/ui/settings-main.js
(and hide the button if there is no URL configured)
> Make the URL of the Help button configurable

- core/client/level-manager.js
- core/client/network-manager.js
- core/client/scenes/scene-world.js
- core/client/user-manager.js
The first step before using directly a socket rather than a document to manage the position of the users.
> Extract network logic to a network-manager file (step 1 before realtime sockets)

- core/client/helpers.js
- core/client/lemverse.js
- core/client/meeting-room.js
- core/client/peer.js
- core/client/user-manager.js
- core/modules/meet/client/meet.js
- Allow developers to implement other services like Zoom, Google Meets, etc.
- Add function to disable meeting rooms
> add proxy around meet

- Dockerfile
- README.md
- app/.meteor/packages
- app/.meteor/versions
- app/_settings.json
- app/settings-dev.json
- core/server/main.js
- core/server/monti.js
[Monti](https://montiapm.com/) is an APM for Meteor apps that has great features such as live CPU profiling, and that's very useful optimize Lemverse. :)
> Monti support

- core/modules/notifications/client/notifications.hbs.html
- core/modules/notifications/client/notifications.js
- core/modules/notifications/client/notifications.scss
- core/server/users.js
+ Add a button to mark all notifications as read
Image when the button is hover:
> Mark all notifications as read

- core/client/ui/settings-medias.hbs.html
- core/client/ui/settings-medias.scss
Add scroll bar to media settings container
> fixes #169: add scroll bar to media settings

- core/client/components/character.js
- core/client/network-manager.js
- core/client/user-manager.js
Fixes the problem of guests not having a skin and being invisible to everyone
Fix #168
> characters: fix guest character animation

- core/lib/misc.js
- core/modules/messages/server/messages.js
- core/modules/notifications/client/notifications.hbs.html
- core/modules/notifications/client/notifications.js
Actually we don't receive any notification if we receive message on global channels. No pop-in or something is triggered. Now we receive notification like in one & one notifications
> Fix notifications not received on global chat

- core/client/helpers.js
- core/client/scenes/scene-loading.js
- core/client/scenes/scene-ui.js
Use canvas to set simulation viewport size
> Fix viewport size

- core/client/components/character-name-text.js
- core/client/components/character.js
- core/client/scenes/scene-ui.js
- core/client/ui/team-profile.scss
- core/client/ui/user-list.hbs.html
- core/client/ui/user-list.js
- core/client/ui/user-list.scss
- core/client/user-manager.js
- core/server/users.js
Add a team icon next to the username and in the user list:
Here is an example of how to create a guild:
1. Upload a team icon as an asset in the editor
2. Get the icon id in the `Files` collection
3. Create the guild in the `guilds` collection (replace the `icon.fileId` with the correct id)
```json
{
"_id": "gui_bZdBbTt5xRN7nAup5",
"createdAt": {
"$date": {
"$numberLong": "1663667575055"
}
},
"name": "Refty",
"description": "Le recrutement nouvelle génération.",
"website": "https://www.refty.co/",
"logo": "https://d3m90ikr40n4n5.cloudfront.net/refty/refty-white.png",
"icon": {
"fileId": "hWssnvrc5KexTbpvt",
"width": 16,
"height": 16
}
}
```
4. Add the attribute `guildId: "gui_bZdBbTt5xRN7nAup5"` to a `user`
> Add team icon

- core/client/level-manager.js
- core/client/scenes/scene-editor.js
This PR consists in adding the visualization of the tiles in the editor mode. Indeed, it allows putting tiles differently than blindly.
This is useful when you place several tiles in one go.
[video](https://user-images.githubusercontent.com/34689945/194087134-8a8a6291-84d3-444d-968f-af2507aa7964.mp4)
> Add preview in the editor

- README.md
- core/client/components/character-name-text.js
- core/client/scenes/scene-ui.js
- core/client/ui/settings-basic.hbs.html
This PR builds on top of #118, only the last commit is relevant. :)
> Display a color picker when name colors are not configured

- core/lib/misc.js
- core/server/accounts.js
- core/server/users.js
A user should spawn in the current level instead of the default level when his position is not set.
> Fix spawn behavior when position is not set

- core/modules/messages/client/messages-list.js
- core/modules/messages/client/messages.js
- core/modules/messages/misc.js
- core/modules/messages/server/messages.js
- core/server/levels.js
- core/server/users.js
The idea is to be able to subscribe to something other than zones to be notified of new content.
> Allow user to subscribe to the level channel

- core/client/scenes/scene-editor.js
This PR adds the copy and paste.
The mode is bound on the shift key.
https://user-images.githubusercontent.com/34689945/194817102-98eca567-12c9-4e1c-a99b-2dc4eb21a6df.mp4
> Add copy paste with preview

- core/client/ui/toolboxes/entity-editor.scss
- core/client/ui/toolboxes/entity-template-list.hbs.html
- core/client/ui/toolboxes/entity-template-list.js
- core/client/ui/toolboxes/entity-template-list.scss
- core/client/ui/toolboxes/entity-toolbox.hbs.html
- core/client/ui/toolboxes/entity-toolbox.js
+ Fix a bug on the editing window scroll. The scrolling wasn't working and overlapping other UI elements.
+ Add support for creating prefabs directly in the editor.
+ Add support for editing prefabs directly in the editor.
Added in [`784ecb0` (#28)](https://github.com/Refty/lemverse/pull/28/commits/784ecb0c156e1566956f6f7fd30b9b6194bf07b5)
> Entity prefab manager

- core/client/scenes/scene-editor.js
Fix a bug with the tile index 0.
Fix a bug where copy pasting from outside of the canvas would crash the editor
> Fix bugs on the preview

- README.md
- app/package-lock.json
- app/package.json
- app/settings-dev.json
- core/collections.js
- core/lib/file-storage.js
+ add support for aws S3 bucket to store files
- upload file on the bucket
- retrieve file on the bucket
- delete file
+ add support for a Content delivery network
- retrieve file of the bucket using a CDN
> Support for online FilesCollection

- core/client/entity-manager.js
- core/client/helpers.js
- core/client/lemverse.js
- core/client/scenes/scene-world.js
- core/client/ui/toolboxes/entity-editor.hbs.html
- core/client/ui/toolboxes/entity-editor.js
- core/client/ui/toolboxes/entity-editor.scss
- core/client/url-opener.js
- core/client/user-manager.js
- core/client/zone-manager.js
Extract the URL opening logic from the zones. This will be useful to be able to open URLs from other events, for example from entities.
I took the opportunity to automatically handle the integration of YouTube videos.
> Extract logic to open URLs from zones

- core/client/ui/user-onboarding.hbs.html
- core/client/ui/user-onboarding.js
- core/client/ui/user-onboarding.scss
Handle other layout keyboards, there is only one thing left. Determine if it's Qwerty or Azerty.. I've tried to use something like this https://stackoverflow.com/a/59113178 or directly using hotkeys.trigger() and determine is keyCode. But none of them worked. Is there any solution to determine the layout of a keyboard actually @Donorhan ?
> Use event.KeyCode on keyboard to trigger all layout keyboards

- core/client/helpers.js
Oops, I've made a little mistake on the last PR, should be good now, sorry @Donorhan 😐
> Fix wrong data fields fetch on canAnswerCall()

- core/client/lemverse.scss
> Adjust z-index of webpage to be ahead of other elements

- core/client/scenes/scene-editor.js
This pull request allows the user to see the colliders while editing the entities.
https://user-images.githubusercontent.com/34689945/203978685-9942eebe-aef4-4d5d-b266-022464712f30.mp4
> Add visualization on colliders
